### ISSUE TITLE
How to emit \nopagebreak?

### ISSUE THREAD

**Issue by peti** [Daniel-Diaz/HaTeX#128]
HaTeX offers `nopagebreak`, which requires an optional parameter `n` that's formatted as:

    \nopagebreak[n]

However, I need 

    \nopagebreak

which *requires* that the page isn't broken here, whereas the argument-variant of the command encodes a weighed recommendation.

I tried `nopagebreak mempty`, but the resulting `\nopagebreak[]` is a syntax error according to LaTeX.

Now, how do I get the parameter-less command (other than `comm0 "nopagebreak"` that is, which I am using right now as a workaround)?

**Comment by Daniel-Diaz** [comment]
I think this is a bug in `nopagebreak`. If the parameter is optional, it should have type `Maybe l` and not `l`. Right now it is forcing you to provide it.

**Comment by Daniel-Diaz** [comment]
I changed the type of `nopagebreak` to make it actually optional in https://github.com/Daniel-Diaz/HaTeX/commit/fefafd75ee9ae070e3e5cd12b50af5741445a7d3. This is however a breaking change and will require a mejor version bump.

**Comment by peti** [comment]
@Daniel-Diaz, I would suggest making the exact same change to `\pagebreak`, too.

**Comment by Daniel-Diaz** [comment]
@peti Yes, you are right.
