### ISSUE TITLE
Parsing fails with `--quickcheck-replay=594248`

### ISSUE THREAD

**Issue by KommuSoft** [Daniel-Diaz/HaTeX#132]
When I ran the tests multiple times, after ~10 runs, I got an error for the parsing module with `--quickcheck-replay=594248`.

It fails with:

```
    render . parse = id: FAIL
      *** Failed! Falsified (after 91 tests):
      TeXSeq (TeXComm "gFQaFfEDot" [MSymArg [TeXRaw "RA",TeXBraces (TeXSeq (TeXRaw "i(K(a*'") (TeXRaw "<UNNJRFie/")),TeXBraces (TeXRaw "QYqs")],MParArg [TeXLineBreak Nothing False,TeXRaw "x+FU)>-",TeXCommS "mZRpo",TeXMath Dollar (TeXSeq (TeXLineBreak (Just (In (-88.37704898478161))) False) (TeXMath DoubleDollar (TeXRaw ",k\"je,DV.gH/"))),TeXCommS "dGWSiieU"]]) (TeXComment "vdNkc,rgDbQw")
      Use --quickcheck-replay=594248 to reproduce.
```

**Comment by Daniel-Diaz** [comment]
Yes, this is a known issue.

https://github.com/Daniel-Diaz/HaTeX/issues/115

**Comment by Daniel-Diaz** [comment]
There is something going on with that test. I am not sure what and I don't currently have time to look at it. But I don't think it's something that would make a valid input fail to parse.

**Comment by leftaroundabout** [comment]
That test case generates `\gFQaFfEDot<RA,{i(K(a*'<UNNJRFie/},{QYqs}>(\\,x+FU)>-,\mZRpo,$\\[-88.37705in]$$,k"je,DV.gH/$$$,\dGWSiieU)%vdNkc,rgDbQw`. I think the problem are the three consecutive `$`s.
