### ISSUE TITLE
Is it time to say goodbye to GHC-7.8?

### ISSUE THREAD

**Issue by leftaroundabout** [Daniel-Diaz/HaTeX#138]
GHC-7.8 was before the applicative-monad change, which programmers now (rightly) assume everywhere. E.g. https://travis-ci.org/Daniel-Diaz/HaTeX/jobs/582615886

Dropping support for this version would solve problems like this. I doubt many people still rely on such an old compiler.

**Comment by leftaroundabout** [comment]
Also https://travis-ci.org/Daniel-Diaz/HaTeX/jobs/586918199

**Comment by Daniel-Diaz** [comment]
Yes, I agree. I am going to remove GHC-7.8 from the Travis build.

**Comment by Daniel-Diaz** [comment]
Done! https://github.com/Daniel-Diaz/HaTeX/commit/405dd6f938de24af7eb9c12412f4f7b4fd186075
