### ISSUE TITLE
Rendering using Builder

### ISSUE THREAD

**Issue by Daniel-Diaz** [Daniel-Diaz/HaTeX#145]
I have run into problems when rendering big LaTeX files.

In an attempt to improve this I have added the `renderBuilder` method to the `Render` typeclass (see https://github.com/Daniel-Diaz/HaTeX/commit/b54323b9f72ed5d29f4968bb85331d6f7bacead8) and defined `render` in terms of `renderBuilder` for some of the instances.

I added this as a new method to keep it backwards-compatible for now. However, it seems to me like the result of `render` should have been `Builder` (or something similar) since the beginning, since rendering a `LaTeX` value usually involves appending many small text pieces.

I understand it would be annoying to the users of HaTeX to change the type signature now, perhaps not even worth it since I defined `render` in terms of `renderBuilder`, giving them the benefits of `Builder` already. However, I think using `renderBuilder` would always be the best option here, so there's no reason to give the two options.

Thoughts? @leftaroundabout

**Comment by leftaroundabout** [comment]
Agree that builder-based seems to be the safe way to go in most cases, but is there any drawback to keeping `render` as a method? For me it was always fine.

In fact, for relatively balanced tree-like content, the performance should at most suffer a constant overhead. In such cases, `render` could also more easily be parallelized (whether anybody would actually do this... not sure).

**Comment by Daniel-Diaz** [comment]
You're right. No real drawback that I can think of. So I will just leave the two options.

Thanks for the feedback!
