### ISSUE TITLE
\author command is obsolete, implement \authorinfo

### ISSUE THREAD

**Issue by philipdexter** [Daniel-Diaz/HaTeX#43]
LaTeX gives the error

```bash
LaTeX Error: The \author command is obsolete; use \authorinfo.
```

As far as I can see, \authorinfo is not implemented. Should this be included in the HaTeX library?

If so, this is a simple implementation which I should get around to soon, just creating this PR to remind myself.

**Comment by Daniel-Diaz** [comment]
I think this is caused by some package you are importing. Could you tell me what packages are you importing in your LaTeX document? Thanks.

**Comment by philipdexter** [comment]
Oh yes, I should have thought of this. This is all defined in the paper template for ACM SIGPLAN. Sorry about the issue!

**Comment by Daniel-Diaz** [comment]
No problem. Thank you for not hesitating in reporting.
