### ISSUE TITLE
latex prettyprinter produces blank lines where none are allowed

### ISSUE THREAD

**Issue by jwaldmann** [Daniel-Diaz/HaTeX#44]
see this ghci session:
```
import Text.LaTeX.Base.Texy
import Text.LaTeX.Packages.AMSMath
import Text.LaTeX.Base.Pretty

putStrLn $ prettyLaTeX $ align_ [   texy ( 1   )]
putStrLn $ prettyLaTeX $ align_ [   texy ( 1,2 )]
```
which gives
```
\begin{align*}
    1
\end{align*}

\begin{align*}
    \left(
    1,2\right)
    
\end{align*}
```
where the first is OK, the second is not.

I really do need the prettyprinter because I want to copy-paste the latex code into a paper,
and possibly edit it - so I need it to be human-readable.

**Comment by jwaldmann** [comment]
I am trying to debug this. I think the reason is `line` items piling up.

`align` uses `TexEnv`

    align_ :: LaTeXC l => [l] -> l
    align_ = liftL(TeXEnv "align*" []) . mconcat . intersperse lnbk 

when this is rendered, there's `line` before `\end`:
```
docLaTeX (TeXEnv n as b) =
  let a = FixArg $ fromString n
  in  mconcat
       [ line
       , docLaTeX $ TeXComm "begin" $ a : as
       , indent 4 $ docLaTeX b
       , line
       , docLaTeX $ TeXComm "end" [a]
         ]
```
but it can happen that inside the `align`, another `line` is produced:
```
texy (x,y) ==> autoParens ... ==> ... commS "right)" ==> ... TexCommS
docLaTeX (TeXCommS n) = backslash <> text n <> line
```
Then we get this:
```
import Text.PrettyPrint.Free
import System.IO

displayIO stdout $ renderSmart 60 $ text "foo" <> line <> text "bar"
```
results in
```
foo
bar
```

but
```
displayIO stdout $ renderSmart 60 $ text "foo" <> line <> line <> text "bar"
```

gives
```
foo

bar
```

**Comment by jwaldmann** [comment]
OK, this is ugly, but it works around that behaviour
```
align' [] = align_ []
align' docs = align_ $ init docs ++ [ last docs <> raw "%" ]
```
at least in the cases that appear in my application https://github.com/jwaldmann/matchbox/blob/master/MB/Proof/LaTeX.hs

**Comment by Daniel-Diaz** [comment]
I think adding lines after every command is too much. Maybe we should change the behavior here. I appreciate your feedback.

**Comment by Daniel-Diaz** [comment]
I made a small change. Now, it should only add a line break after commands if the command ends filling the whole line space. Perhaps I should add some special cases to the pretty-printer. Like adding line breaks for some cases, but not for others. For example, adding a line break after ``\maketitle`` makes a lot of sense to me. But it doesn't for ``\delta``, for instance.
