### ISSUE TITLE
docLaTeX on TeXRaw violates pretty-printer invariants

### ISSUE THREAD

**Issue by rpglover64** [Daniel-Diaz/HaTeX#46]
See also: ekmett/wl-pprint-extras/issues/7

The text under the `TeXRaw` constructor is allowed to have newline characters, but the `text` function from the pretty printer package expects to be passed a string without newlines.

**Comment by Daniel-Diaz** [comment]
We switched to [prettyprinter](http://hackage.haskell.org/package/prettyprinter), and apparently this is no longer an issue with this package. See the [Pretty instance for the Text type](http://hackage.haskell.org/package/prettyprinter-1.3.0/docs/Data-Text-Prettyprint-Doc.html#t:Pretty).
