### ISSUE TITLE
Undefined functions in Num, Floating instances

### ISSUE THREAD

**Issue by dmcclean** [Daniel-Diaz/HaTeX#51]
Right now the `Num` and `Floating` instances for `LaTeX` in the AMSMath package contain errors for certain functions that aren't defined by AMSMath.

Would you accept a patch changing them to use AMSMath's `\operatorname{ }` command?

https://github.com/Daniel-Diaz/HaTeX/blob/master/Text/LaTeX/Packages/AMSMath.hs#L150

```
 -- Non-defined methods
 signum _ = error "Cannot use \"signum\" Num method with a LaTeX value."
```

would become as below, with similar functions for inverse hyperbolic trig functions from `Floating`.

```
 signum = (operatorname "sgn" <>)

-- Whether or not to expose this helper is up for debate.
operatorname :: LaTeXC l => l -> l
operatorname = comm1 "operatorname"
```

`sgn` is the name used [in the wikipedia article](http://en.wikipedia.org/wiki/Sign_function) and is in fairly wide use. `arctanh` etc seem uncontroversial. Obviously clients that are unhappy with it would be free to avoid using these functions as the documentation warns to do today.

**Comment by Daniel-Diaz** [comment]
I would gladly accept such patch. The ``operatorname`` helper should be exported as well, in my opinion. That way, the user would have it easy to add the new names. The only thing I see is that predefined operators (like ``sin``, ``cos``, etc) will be translated by babel, while these locally defined operators won't. This should be warned in the docs.

Thanks!

**Comment by dmcclean** [comment]
The ad8b02a change fixes the spelling problem I was talking about.

**Comment by Daniel-Diaz** [comment]
Now that the suggested patch has been merged, I close this issue.
