### ISSUE TITLE
Symbols not defined in a package

### ISSUE THREAD

**Issue by dmcclean** [Daniel-Diaz/HaTeX#53]
Is it OK to add `\imath` and `\jmath` to the `Text.LaTeX.Packages.AMSMath` module, in spite of the fact that they are technically defined somewhere else and you don't really need the package to use them?

If not, is there some other module where it would be appropriate to add them?

**Comment by Daniel-Diaz** [comment]
What package are these from? Are these commands available once you have imported AMSMath?

**Comment by dmcclean** [comment]
On my computer, which runs MikTeX 2.9, they are in `C:\Program Files (x86)\MiKTeX 2.9\tex\latex\base\fontmath.ltx`, which appears to me (not a TeX expert) to be a base part of all documents and not in any package at all? (Or perhaps it is controlled by which documentclass you pick?) At any rate, they are visible in a document that includes no `\usepackage` commands. They are visible if you do not import AMSMath and remain so if you do.

**Comment by Daniel-Diaz** [comment]
Great! Then they can be added with no problem.

**Comment by Daniel-Diaz** [comment]
Closed after merging https://github.com/Daniel-Diaz/HaTeX/pull/55.
