### ISSUE TITLE
HaTeX-3.16.0.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [Daniel-Diaz/HaTeX#57]
Citing from http://hydra.cryp.to/build/650375/log/raw:

    Preprocessing test suite 'hatex-test' for HaTeX-3.16.0.0...
    [1 of 1] Compiling Main             ( test/Main.hs, dist/build/hatex-test/hatex-test-tmp/Main.dyn_o )

    test/Main.hs:8:10:
        Duplicate instance declarations:
          instance Eq ParseError -- Defined at test/Main.hs:8:10
          instance Eq ParseError
            -- Defined in ‘parsec-3.1.9:Text.Parsec.Error’

**Comment by Daniel-Diaz** [comment]
Hi, @peti . Try `cabal update`. I uploaded a version of HaTeX with this issue fixed earlier today.
