### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by technocrat** [Daniel-Diaz/HaTeX#73]
The intro to the guide states that HaTeX 

> provides functions to create, manipulate and parse LaTeX code

It's unclear from the guide, examples, and comments to the source code, however, whether the user should expect to be able to parse and manipulate a LaTeX code **block.** That is, having imported a well-formed LaTeX object, it is possible to **render** it and to detect some features

```
> lookForCommand "hline" input
```

[[],[],[]]

but functions to change elements in-block appear to be either missing or too obvious to require any indication for the intended audience. (In personal terms, as a newcomer to Haskell, I can't tell whether I'm just missing something blindingly obvious or if what would be required is to build up the functions to do this through finding ways of recombining the existing pieces.)

To give a concrete example of what I am trying to do

{-# LANGUAGE OverloadedStrings #-}

```
module Himport where

import Text.LaTeX
import Text.LaTeX.Base.Parser
import Text.LaTeX.Base.Syntax
import Text.LaTeX.Base.Render
import Data.Either
import Data.Maybe (fromJust)

main = do 
  obj <- parseLaTeXFile "tester.Rmd"
  return obj

fromRight           :: Either a b -> b
fromRight (Left _)  = error "fromRight: Argument takes form 'Left _'" 
fromRight (Right x) = x

getTable :: LaTeX -> Maybe LaTeX
getTable l =
  case lookForEnv "table" l of
    ((_,b):_) -> Just b
    _ -> Nothing
```

I import this into the repl and create a Either ParseError LaTeX object

```
: obj <- main
```

and extract the LaTeX block with

```
: let input = fromRight obj
```

This gives me

```
     TeXSeq (TeXComment " latex table generated in R 3.2.1 by xtable 1.7-4 package") (TeXSeq (TeXComment " Mon Nov  9 21:01:01 2015") (TeXSeq (TeXEnv "table" [OptArg (TeXRaw "ht")] (TeXSeq (TeXRaw "\n") (TeXSeq (TeXCommS "centering") (TeXSeq (TeXRaw "\n") (TeXSeq (TeXEnv "tabular" [FixArg (TeXRaw "rrrrr")] (TeXSeq (TeXRaw "\n  ") (TeXSeq (TeXCommS "hline") (TeXSeq (TeXRaw "\n & Disputed & Firearm & Knife & No ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  ") (TeXSeq (TeXCommS "hline") (TeXSeq (TeXRaw "\nDeath in custody & 0.00 & 0.00 & 0.00 & 3.86 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  Gunshot & 0.30 & 47.92 & 14.24 & 9.50 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  Struck by vehicle & 0.00 & 0.15 & 0.00 & 3.26 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  Taser & 0.00 & 0.00 & 0.15 & 4.60 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  Unknown & 0.00 & 0.00 & 0.00 & 0.45 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n  Sum & 0.30 & 48.07 & 14.39 & 21.66 ") (TeXSeq (TeXLineBreak Nothing False) (TeXSeq (TeXRaw " \n   ") (TeXSeq (TeXCommS "hline") (TeXRaw "\n")))))))))))))))))))))) (TeXSeq (TeXRaw "\n") (TeXSeq (TeXComm "caption" [FixArg (TeXRaw "Causes of 674 civilian deaths by type of weapon carried by civilian, part 1")]) (TeXSeq (TeXRaw " \n") (TeXSeq (TeXComm "label" [FixArg (TeXRaw "2")]) (TeXRaw "\n")))))))))) (TeXRaw "\n")))
```

which is where I'm stuck. Ultimately, I wish to delete the comments and label commands, insert a different line after each of the first two hlines, add text to the beginning of the table line, change the tabular justification of the first column, insert some text at the beginning of a specific row, change capitalization and convert "0.00" to "."  These are all things I can do to strings, already, using regex, but that seem a clumsy translation from the imperative world.

If the functions are there and non-obvious, a hint would help or if they are not included a mention that the flow all goes into a LaTeX block and from there it can only be rendered, if any further changes or necessary the block must be reassembled from its pieces.

Very comprehensive package that should become a backbone for lhs. Thanks.

**Comment by Daniel-Diaz** [comment]
Thanks for the elaborated issue ticket, and apologies for a late response.

Currently, the only helper functions to manipulate ``LaTeX`` values are under the _Syntax Analysis_ section of the [Text.LaTeX.Base.Syntax](http://hackage.haskell.org/package/HaTeX-3.16.2.0/docs/Text-LaTeX-Base-Syntax.html#g:3) module (as of version 3.16.2.0). These are few and probably limited in their usefulness. I added them as part of an experiment to see if people would like more work into that direction. However, manipulation of ``LaTeX`` values might be hard in some cases. For example, things like tables and numbers are considered text, so transformations on these things are tedious. They are possible, but it would require dissecting the ``LaTeX`` block using its constructors. Still better than plain text.

Removing comments should be really easy though:

```haskell
removeComments :: LaTeX -> LaTeX
removeComments = texmap isComment (const mempty)
  where
    isComment (TeXComment _) = True
    isComment _ = False
```

I didn't try the code myself, but I think it should work.
