### ISSUE TITLE
Should we try to get HaTeX more compatible with lenses?

### ISSUE THREAD

**Issue by leftaroundabout** [Daniel-Diaz/HaTeX#74]
[Lenses](http://hackage.haskell.org/package/lens) are getting increasingly ubiquitous in the Haskell world. (I consider this a good thing.) In virtually everything I'm doing now there's at least one library involved that uses them.

It's generally not a problem to combine libraries using lenses with ones that don't; with HaTeX in particular there's one rather trivial issue that it defines [`(&)`](http://hackage.haskell.org/package/HaTeX-3.16.2.0/docs/Text-LaTeX-Base-Commands.html#g:22) as the column seperation operator, while lens uses [`(&)`](http://hackage.haskell.org/package/lens-4.13/docs/Control-Lens-Lens.html#v:-38-) as flipped function-application. It's easy to resolve this with qualified imports, but still a bit tedious. Should we rename it to `(&:)`, keeping with the scheme already used for several other operators in HaTeX ([`(=:)`](http://hackage.haskell.org/package/HaTeX-3.16.2.0/docs/Text-LaTeX-Packages-AMSMath.html#g:12), [(`!:`)](http://hackage.haskell.org/package/HaTeX-3.16.2.0/docs/Text-LaTeX-Packages-AMSMath.html#g:6), [(`%:`)](http://hackage.haskell.org/package/HaTeX-3.16.2.0/docs/Text-LaTeX-Base-Commands.html)...)?

While on the subject, would it be worthwhile to _use_ lenses in HaTeX itself? (Perhaps the answer is just _no_, since there aren't many record types &ndash; are any exposed at all?)

**Comment by Daniel-Diaz** [comment]
I don't think bringing lenses power to HaTeX would be useful in practice (any examples to prove me wrong?). However, you do have a point regarding their common use and the conflict between the two ``(&)``. However, I am not sure this is a good reason to include a breaking change. There is even a book using HaTeX's ``(&)``. I assume many people code will break if we change it now.

**Comment by leftaroundabout** [comment]
You're probably right that this issue is needless – it's easy enough to `import Text.LaTeX hiding ((&))`.
