### ISSUE TITLE
Compile Time Error for HaTeX 3.17.0.0

### ISSUE THREAD

**Issue by 2016rshah** [Daniel-Diaz/HaTeX#80]
I get the following compile time error when I try to install HaTeX 3.17.0.0 from Hackage:

```

[15 of 34] Compiling Text.LaTeX.Base.Parser ( Text/LaTeX/Base/Parser.hs, dist/build/Text/LaTeX/Base/Parser.o )

Text/LaTeX/Base/Parser.hs:364:32:
    No instance for (Stream Text Data.Functor.Identity.Identity Char)
      arising from a use of ‘char’
    In the first argument of ‘(*>)’, namely ‘char '.'’
    In the second argument of ‘(<$>)’, namely
      ‘(char '.' *> (some digit <?> "fraction"))’
    In the expression:
      foldr op 0.0 <$> (char '.' *> (some digit <?> "fraction"))

Text/LaTeX/Base/Parser.hs:375:18:
    No instance for (Stream Text Data.Functor.Identity.Identity Char)
      arising from a use of ‘char’
    In the second argument of ‘(<$)’, namely ‘char '-'’
    In the first argument of ‘(<|>)’, namely ‘negate <$ char '-'’
    In the first argument of ‘(<|>)’, namely
      ‘negate <$ char '-' <|> id <$ char '+'’
World file is already up to date.
cabal: Error: some packages failed to install:
HaTeX-3.17.0.0 failed during the building phase. The exception was:
ExitFailure 1

```

**Comment by leftaroundabout** [comment]
Please always add version numbers for compiler and package dependencies, when submitting bug reports!

    grep -A10 depends dist/package.conf.inplace/HaTeX-3.17.0.0-inplace.conf

For me the works, with GHC-7.10.2,

    QuickCheck-2.8.1-b8cde035baf86e10569b5c8f1da0c941
    base-4.8.1.0-4f7206fd964c629946bb89db72c80011
    bytestring-0.10.6.0-2362d1f36f1255e85478e7793e15b170
    containers-0.5.6.2-2de75421d746ab474b330e43191bb31b
    matrix-0.3.4.4-23cbb6f1c002e1b10b5b62d040c4ab2e
    parsec-3.1.9-2a345832274797fcf12a14e7adb52197
    text-1.2.1.3-202edba6fea901191194d38d810da662
    transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff
    wl-pprint-extras-3.5.0.5-3304b0292643f776b82f3ae7e825b48c

**Comment by Daniel-Diaz** [comment]
I uploaded version 3.17.0.1 to Hackage. It should have this issue fixed.

Thanks for the info.

**Comment by 2016rshah** [comment]
It fixed the issue for me, everything works great now 👍

**Comment by Daniel-Diaz** [comment]
Awesome!
