### ISSUE TITLE
Add examples of how to draw linked nodes with TikZ

### ISSUE THREAD

**Issue by romildo** [Daniel-Diaz/HaTeX#82]
It is not clear to me how to draw linked nodes using the `Text.LaTeX.Packages.TikZ`. Please, add examples of it.

For instance, how to translate the following LaTeX code to HaTeX?

``` latex
\documentclass[convert]{standalone}

\usepackage{tikz}

\begin{document}

\begin{tikzpicture}[node distance=3cm]
  \node[rectangle,draw](a){First Node};
  \node[][right of=a](b){Second\\Node};
  \node[circle,draw,fill=blue!30][right of=b](c){Third\\Node}
    edge [->, bend right=45] node[auto,swap]{$x$}(a);
\end{tikzpicture}

\end{document}
```

The typeset document gives:
![tikz-linked-nodes](https://cloud.githubusercontent.com/assets/1217934/16356294/2619b9a4-3aa9-11e6-841b-23d473e21cca.png)

**Comment by Daniel-Diaz** [comment]
Sorry, but node connectors have not been implemented in `Text.LaTeX.Packages.TikZ` yet, so I don't thing there is a direct translation from that code to HaTeX.
