### ISSUE TITLE
pmatrix

### ISSUE THREAD

**Issue by joecefnhedog** [Daniel-Diaz/HaTeX#86]
If` I had a matrix like:
( "L" "M_R" )
( "M_R" "L_R" )

`lMatrix =[["L","M_R"],["M_R","L_R"]]`
`lMatrix2 :: Monad m => LaTeXT_ m`
`lMatrix2= pmatrix Nothing $ (fromLists lMatrix)`

how could I get this to latex without it inserting {} between spaces.
so this is what i'm getting;

\begin{pmatrix}L&M_{}R\M_{}R&L_{}R\\end{pmatrix}

and this is what I want

\begin{pmatrix}L&M_R\\M_R&L_R\\\end{pmatrix}.

**Comment by leftaroundabout** [comment]
So you want something like this?

<table><tr><td><i>L</i></td><td><i>M<sub>R</sub></i></td></tr><tr><td><i>M<sub>R</sub></i></td><td><i>L<sub>R</sub></i></td></tr></table>

For _subscripts_ better use [`!:`](http://hackage.haskell.org/package/HaTeX-3.17.0.2/docs/Text-LaTeX-Packages-AMSMath.html#g:6), raw `_` is infamous for “double subscript” kind of runtime errors.

Or is this actually supposed to display as _underscores_?

**Comment by Daniel-Diaz** [comment]
Closing this one! Thanks for answering at the time @leftaroundabout !
