### ISSUE TITLE
derive Generic and Data type class instance for LaTeX type

### ISSUE THREAD

**Issue by HaskellZhangSong** [Daniel-Diaz/HaTeX#89]
Could you make LaTeX Generic and Data typeclass instance so that user can use syb and ADT generic related function to transform and process tex document?

**Comment by siddharthist** [comment]
I would love to see `Typeable` as well, for the extensible-effects library. @Daniel-Diaz I'm happy to make a PR for these instances if you'd be willing to accept it!
