### ISSUE TITLE
How do lookForCommand and lookForEnv work?

### ISSUE THREAD

**Issue by siddharthist** [Daniel-Diaz/HaTeX#90]
I've tried to use `lookForCommand` and `lookForEnv` in the ways that seem most intuitive based on their descriptions, but they always seem to return an empty list. Moreover, I can't find tests in this codebase for these functions to use as examples. Here's what I've tried:
```
*Main Text.LaTeX.Base.Syntax Text.LaTeX> lookForCommand "author" (raw "\\author{Me}")
[]
*Main Text.LaTeX.Base.Syntax Text.LaTeX> lookForEnv "env" (raw "\\begin{env}env\\end{env}")
[]
```
The expected behavior is that these functions find the respective commands and environments, along with their arguments. 

Can you help me understand what I've missed?

**Comment by Daniel-Diaz** [comment]
You are inserting the TeX code using `raw`. This will insert raw text that won't be recognized as command or environment. Use the LaTeX parser instead. For example:

```
? lookForCommand "author" <$> parseLaTeX "\\author{Me}"
Right [[FixArg (TeXRaw "Me")]]
```

**Comment by siddharthist** [comment]
@Daniel-Diaz Ah, thank you! So obvious now :)
