### ISSUE TITLE
How to use 'S' column types from siunitx in HaTeX-generated tables?

### ISSUE THREAD

**Issue by peti** [Daniel-Diaz/HaTeX#97]
I'm trying to render a table with a column of aligned numbers as recommended in https://tex.stackexchange.com/questions/2746/aligning-numbers-by-decimal-points-in-table-columns, but it seems there's no way to specify the `S` column type in a `tabular` environment. Am I missing something terribly obvious?

**Comment by romildo** [comment]
PR https://github.com/Daniel-Diaz/HaTeX/pull/95 adds some new form of column types. One of the new constructors is `NameColumn :: String -> TableSpec`, which can be helpful in your use case. The original idea is to allow column types like the common `X` from `tabularx`,  and user defined column types.

I hope the PR is reviewed and merged soon.

**Comment by peti** [comment]
`NameColumn` sounds like the way to go. It's kind-of unsafe to have that constructor, but at the same time the notion of offering a special constructor for every kind of column type people are going to invent, ever, is probably unrealistic.

**Comment by Daniel-Diaz** [comment]
Since #95 was merged, is this still an issue?

**Comment by peti** [comment]
I haven't actually tried it yet, but from the looks of it the problem is solved by that PR.  Will there be an update to Hackage that contains these changes?

**Comment by Daniel-Diaz** [comment]
Yes, I will make a release very soon.

**Comment by Daniel-Diaz** [comment]
HaTeX-3.17.3.0 released.

http://hackage.haskell.org/package/HaTeX-3.17.3.0
